version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: products-postgres
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - products-network

  products-api:
    build: .
    container_name: products-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
    networks:
      - products-network

volumes:
  postgres_data:

networks:
  products-network:
    driver: bridge
